#!/bin/bash

DYNAMODB_ENDPOINT=http://localstack:4569
S3_ENDPOINT=http://localstack:4572
TABLE_NAME=examples-table
BUCKET_NAME=examples-bucket

docker-compose exec awscli aws dynamodb create-table \
    --table-name ${TABLE_NAME} \
    --attribute-definitions \
        AttributeName=Id,AttributeType=S \
    --key-schema AttributeName=Id,KeyType=HASH \
    --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 \
    --endpoint-url ${DYNAMODB_ENDPOINT}

docker-compose exec awscli aws dynamodb put-item \
    --table-name ${TABLE_NAME} \
    --item \
        '{"Id": {"S": "test"}, "Column1": {"S": "test1"}, "Column2": {"S": "test2"}, "Column3": {"S": "test3"}}' \
    --endpoint-url ${DYNAMODB_ENDPOINT}

docker-compose exec awscli aws s3api create-bucket \
    --bucket ${BUCKET_NAME} \
    --endpoint-url ${S3_ENDPOINT}
